api:
 id: "15687136"
 http:
  listener:
   path: "/*"
   host: "0.0.0.0"
   port: "8091"
  response:
   timeout: "300000"

reconnect:
 freq: "1000"
 attempts: "3"
 timeout: "30000"
  
http:
 sys:
  bat:
   host: "localhost"
   port: "8092"
   path:
    empdetails: "employeeDetails"
    activeuserid: "activeUserId"

targetFlag: "true"
appId: "004"
    
#common:
# requester:
#  configref: "HTTP_Request_configuration_without_TLS"
#  host: "localhost"
#  port: "8091"
#  basepath: ""
#  path: "/errorMappings"
# connection:
#  frequency: "1000"
#  retrycount: "3"
#  responsetimeout: "30000"   
common:
 requester:
  configref: "HTTP_Request_configuration_with_TLS"
  host: "dev-int.bat.net"
  port: "443"
  basepath: ""
  path: "/s-common-error-handler-v2-dev/errorMappings"
 connection:
  frequency: "1000"
  retrycount: "3"
  responsetimeout: "30000"