api:
 id: "15719484"
 http:
  listener:
   path: "/*"
   host: "0.0.0.0"
   port: "8091"
  response:
   timeout: "30000"

reconnect:
 freq: "1000"
 attempts: "3"
 
http:
 sys:
  bat:
   host: "mule-worker-internal-system-hr-sf-employeedetails-v2.de-c1.cloudhub.io"
   port: "8091"
   path:
    empdetails: "employeeDetails"
    activeuserid: "activeUserId"   