api:
 id: "157194846546"
 http:
  listener:
   path: "/*"
   host: "0.0.0.0"
   port: "8091"
  response:
   timeout: "30000"

reconnect:
 freq: "1000"
 attempts: "3"
 
http:
 sys:
  bat:
   host: "0.0.0.0"
   port: "8091"
   path:
    empdetails: "employeeDetails"
    activeuserid: "activeUserId"   
